[tools]

act = "latest"
just = "latest"
k3d = "latest"
sqlc = "latest"

go = ["latest"]
golangci-lint = "latest"
gofumpt = "latest"
"go:github.com/securego/gosec/v2/cmd/gosec" = "latest"
"go:golang.org/x/vuln/cmd/govulncheck" = "latest"

java = "lts"
gradle = "latest"

node = "lts"
bun = "latest"

python = "latest"

mongodb = "latest"
mongosh = "latest"

[env]
# _.python.venv = "{{env.PWD}}/.venv"

[settings]
python.uv_venv_auto = true
